version: "3.7"
services:
  api_service:
    image: luffy:1.0.2-STABLE-SNAPSHOT
    restart: always
    container_name: 'luffy'
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=mongodb://mongo
      - SPRING_RABBITMQ_HOST=rabbitmq

  mongo:
    image: mongo
    restart: always
    container_name: 'mongoDB'
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"