version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
#    links:
#      - mongo:service_db # add variable to dockerfile for host.docker.internal
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"