# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# after completion it'll publish and release the build artifacts and deploy to aws

name: Java release artifact

on:
  push:
    tags:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
          - 15672:15672

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '4.4'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: target/*.jar

      - name: Get Version
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11}) # changed 10 -> 11 for ignoring "v" in docker

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Change wrapper permissions
        run: chmod +x ./mvnw
      - name: Build Image
        run: ./mvnw spring-boot:build-image

      - name: Push Image
        run: docker push anshulsaraf/luffy:${{env.RELEASE_VERSION}}

      - name: Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/Luffy.jar"
          token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Deploy Artifacts
#        uses: einaregilsson/beanstalk-deploy@v18
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          application_name: Luffy
#          environment_name: Luffy-env
#          version_label: "${{env.RELEASE_VERSION}}"
#          region: ap-south-1
#          deployment_package: "target/NarutoDB.jar"